"""

Commit message: added telegram vacancy
Revision ID: e4a00f693ed4
Revises: ee7ce470e504
Create Date: 2025-06-18 14:47:05.857797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4a00f693ed4'
down_revision: Union[str, None] = 'ee7ce470e504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_vacancy',
    sa.Column('channel_link', sa.String(length=143), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=4096), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('hash'),
    sa.UniqueConstraint('channel_link', 'message_id', name='uq_telegram_vacancy_channel_message'),
    sa.UniqueConstraint('hash'),
    schema='parser'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_vacancy', schema='parser')
    # ### end Alembic commands ###
