[project]
name = "telegram-bot"
dynamic = ["version"]
dependencies = [
    "aiogram>=3.20.0.post0",
    "alembic>=1.16.2",
    "asyncpg>=0.30.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
]
