services:
  parser-service:
    container_name: parser-service
    build:
      context: .
      dockerfile: ./services/parser-service/Dockerfile
      target: ${ENV_MODE}
    volumes:
      - ./services/parser-service/src:/app/services/parser-service/src
      - ./libs/logger:/app/libs/logger
