services:
  postgres:
    image: postgres:17.5-alpine
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 5s

  parser:
    container_name: parser
    build:
      context: .
      dockerfile: services/parser/Dockerfile
      target: ${ENV_MODE}
    env_file: .env
    volumes:
      - ./services/parser/src:/app/services/parser/src
      - ./libs:/app/libs

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  gpt-api:
    container_name: gpt-api
    build:
      context: .
      dockerfile: services/gpt-api/Dockerfile
      target: ${ENV_MODE}
    env_file: .env
    ports:
      - "${GPT_API_PORT}:${GPT_API_PORT}"
    volumes:
      - ./services/gpt-api/src:/app/services/gpt-api/src
      - ./libs:/app/libs
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://gpt-api:${GPT_API_PORT}/health" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

  telegram-parser-api:
    container_name: telegram-parser-api
    build:
      context: .
      dockerfile: services/telegram-parser-api/Dockerfile
      target: ${ENV_MODE}
    env_file: .env
    ports:
      - "${TELEGRAM_PARSER_API_PORT}:${TELEGRAM_PARSER_API_PORT}"
    volumes:
      - ./services/telegram-parser-api/src:/app/services/telegram-parser-api/src
      - ./libs:/app/libs
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://telegram-parser-api:${TELEGRAM_PARSER_API_PORT}/health" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s


networks:
  app-network:
    driver: bridge


volumes:
  postgres-data:
