name: ${ENV_PROJECT_NAME}


services:
  parser-service:
    build:
      context: ./services/parser-service/
      target: ${ENV_MODE}
    env_file:
      - .env
    volumes:
      - ./services/parser-service/src:/app/services/parser-service/src