[project]
name = "sync-it"
dynamic = ["version"]
requires-python = ">=3.13"
dependencies = [
]

[dependency-groups]
dev = []

[tool.setuptools.packages.find]
where = ["libs/common", "services"]

[tool.uv.sources]
gpt-api = { workspace = true }
telegram-parser-api = { workspace = true }
vacancy-parser = { workspace = true }

[tool.uv.workspace]
members = [
    "libs/common/database",
    "libs/common/redis-lib",
    "services/gpt-api",
    "services/telegram-parser-api",
    "services/vacancy-parser",
]
