[project]
name = "syncit"
version = "0.1.0"
requires-python = "==3.13.4"
dependencies = [
    "parser",
    "alembic>=1.16.1",
    "asyncpg>=0.30.0",
    "pydantic>=2.11.6",
    "pydantic-settings>=2.9.1",
    "sqlalchemy>=2.0.41",
    "uvloop>=0.21.0",
    "greenlet>=3.2.3",
]


[dependency-groups]
dev = [
    "hupper>=1.12.1",
    "isort>=6.0.1",
    "mypy>=1.16.0",
    "ruff>=0.11.13",
]

[tool.uv.sources]
parser = { workspace = true }

[tool.uv.workspace]
members = ["services/parser"]

[tool.ruff]
fix = true
unsafe-fixes = true
line-length = 120
lint.preview = true
lint.select = ["ALL"]
lint.ignore = ["I", "D", "DOC", "CPY001", "COM812"]
extend-exclude = ["libs/database/migrations"]

[tool.mypy]
mypy_path = "services/parser/src"
plugins = "pydantic.mypy, sqlalchemy.ext.mypy.plugin"
incremental = true
warn_return_any = true
warn_unused_configs = true
show_error_context = true
disallow_subclassing_any = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
follow_imports_for_stubs = true
explicit_package_bases = true

[tool.isort]
profile = "black"
lines_after_imports = 2
line_length = 120
force_sort_within_sections = true
float_to_top = true
