services:
  api-gateway:
    container_name: api-gateway
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-api-gateway:latest
    env_file: ${SERVICE_PROJECT_ROOT}/infra/.env
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://api-gateway:${API_GATEWAY_PORT}/health" ]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 3s
