x-service-common: &service-common
    build:
      context: ${PROJECT_ROOT}
      dockerfile: infra/docker/vacancy-parser/Dockerfile
      target: ${ENV_MODE}
    env_file: ${PROJECT_ROOT}/infra/.env
    volumes:
        - ${PROJECT_ROOT}/services/vacancy-parser:/app/services/vacancy-parser
        - ${PROJECT_ROOT}/libs:/app/libs
    networks:
      - app-network

x-healthcheck-common: &healthcheck-common
    interval: 30s
    timeout: 3s
    retries: 3
    start_period: 3s
    start_interval: 1s

services:
  vacancy-parser:
    <<: *service-common
    container_name: vacancy-parser
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://vacancy-parser:${ENV_SERVICE_INTERNAL_PORT}/health" ]
      <<: *healthcheck-common

  vacancy-parser-worker:
    <<: *service-common
    container_name: vacancy-parser-worker
    command: [ "celery", "-A", "celery_app.app", "worker", "-l", "${LOG_LEVEL}" ]
    healthcheck:
      test: [ "CMD-SHELL", "celery -A celery_app.app inspect ping -d celery@$$HOSTNAME" ]
      <<: *healthcheck-common

  vacancy-parser-beat:
    <<: *service-common
    container_name: vacancy-parser-beat
    command: [ "celery", "-A", "celery_app.app", "beat", "-l", "${LOG_LEVEL}" ]

  vacancy-parser-flower:
    <<: *service-common
    container_name: vacancy-parser-flower
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    command: [ "celery", "-A", "celery_app.app", "flower", "-l", "${LOG_LEVEL}" ]
