services:
  telegram-bot:
    container_name: telegram-bot
    build:
      context: ${PROJECT_ROOT}
      dockerfile: infra/docker/telegram-bot/Dockerfile
      target: ${ENV_MODE}
    env_file: ${PROJECT_ROOT}/infra/.env
    volumes:
      - ${PROJECT_ROOT}/services/telegram-bot:/app/services/telegram-bot
      - ${PROJECT_ROOT}/libs:/app/libs
    networks:
      - app-network
