services:
  telegram-bot:
    container_name: telegram-bot
    build:
      context: ${PROJECT_ROOT}
      dockerfile: infra/docker/telegram-bot/Dockerfile
      target: ${ENV_MODE}
    env_file: ${PROJECT_ROOT}/infra/.env
    volumes:
      - ${PROJECT_ROOT}/services/telegram-bot:/app/services/telegram-bot
      - ${PROJECT_ROOT}/libs:/app/libs
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://telegram-bot:${ENV_SERVICE_INTERNAL_PORT}/health" ]
      interval: 15s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 1s
