services:
  telegram-bot:
    container_name: telegram-bot
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-telegram-bot:latest
    env_file: ${SERVICE_PROJECT_ROOT}/infra/.env
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://telegram-bot:${ENV_SERVICE_INTERNAL_PORT}/health" ]
      interval: 15s
      timeout: 1s
      retries: 3
      start_period: 30s
      start_interval: 1s
