"""added user preference

Revision ID: 8e1729264724
Revises: d01531d88218
Create Date: 2025-07-24 19:31:44.684937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1729264724'
down_revision: Union[str, Sequence[str], None] = 'd01531d88218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_bot.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='telegram_bot'
    )
    op.create_index(op.f('ix_telegram_bot_user_preference_category_code'), 'user_preference', ['category_code'], unique=False, schema='telegram_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_bot_user_preference_category_code'), table_name='user_preference', schema='telegram_bot')
    op.drop_table('user_preference', schema='telegram_bot')
    # ### end Alembic commands ###
