"""added unique constraint for user preference

Revision ID: 60065ed724ba
Revises: 8e1729264724
Create Date: 2025-07-26 09:08:10.937224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60065ed724ba'
down_revision: Union[str, Sequence[str], None] = '8e1729264724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_category_item', 'user_preference', ['user_id', 'category_code', 'item_id'], schema='telegram_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_category_item', 'user_preference', schema='telegram_bot', type_='unique')
    # ### end Alembic commands ###
