"""added user fields

Revision ID: d01531d88218
Revises: 3a4df4499795
Create Date: 2025-07-07 15:21:05.988888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01531d88218'
down_revision: Union[str, Sequence[str], None] = '3a4df4499795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=32), nullable=True), schema='telegram_bot')
    op.add_column('user', sa.Column('first_name', sa.String(length=64), nullable=False), schema='telegram_bot')
    op.add_column('user', sa.Column('last_name', sa.String(length=64), nullable=True), schema='telegram_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name', schema='telegram_bot')
    op.drop_column('user', 'first_name', schema='telegram_bot')
    op.drop_column('user', 'username', schema='telegram_bot')
    # ### end Alembic commands ###
