name: ${ENV_PROJECT_NAME}

services:
  gpt-api:
    ports:
      - "${GPT_API_PORT}:${ENV_SERVICE_INTERNAL_PORT}"

  telegram-api:
    ports:
      - "${TELEGRAM_API_PORT}:${ENV_SERVICE_INTERNAL_PORT}"

  vacancy-parser:
    ports:
      - "${VACANCY_PARSER_PORT}:${ENV_SERVICE_INTERNAL_PORT}"

  vacancy-processor:
    ports:
      - "${VACANCY_PROCESSOR_PORT}:${ENV_SERVICE_INTERNAL_PORT}"

  telegram-bot:
    ports:
      - "${TELEGRAM_BOT_PORT}:${ENV_SERVICE_INTERNAL_PORT}"
    healthcheck:
      test: [ "CMD", "true" ] # supress because webhook may be disabled