services:
  telegram-api:
    container_name: telegram-api
    build:
      context: ${PROJECT_ROOT}
      dockerfile: infra/docker/telegram-api/Dockerfile
      target: ${ENV_MODE}
    env_file: ${PROJECT_ROOT}/infra/.env
    volumes:
      - ${PROJECT_ROOT}/services/telegram-api:/app/services/telegram-api
      - ${PROJECT_ROOT}/libs:/app/libs
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://telegram-api:${ENV_SERVICE_INTERNAL_PORT}/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 7s
      start_interval: 1s
