services:
  telegram-api:
    container_name: telegram-api
    build:
      context: ${PROJECT_ROOT}
      dockerfile: infra/docker/telegram-api/Dockerfile
      target: ${ENV_MODE}
    env_file: ${PROJECT_ROOT}/infra/.env
    ports:
      - "${TELEGRAM_API_PORT}:${TELEGRAM_API_PORT}"
    volumes:
      - ${PROJECT_ROOT}/services/telegram-api/src:/app/services/telegram-api/src
      - ${PROJECT_ROOT}/libs:/app/libs
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://telegram-api:${TELEGRAM_API_PORT}/health" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s