services:
  telegram-api:
    container_name: telegram-api
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-telegram-api:latest
    env_file: ${SERVICE_PROJECT_ROOT}/infra/.env
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://telegram-api:${ENV_SERVICE_INTERNAL_PORT}/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 7s
      start_interval: 1s
