"""added telegram vacancy

Revision ID: 3fac6d6b96bc
Revises: 0d01a329e26b
Create Date: 2025-06-20 11:57:32.778581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fac6d6b96bc'
down_revision: Union[str, Sequence[str], None] = '0d01a329e26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_vacancy',
    sa.Column('channel_link', sa.String(length=143), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=4096), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('hash'),
    sa.UniqueConstraint('channel_link', 'message_id', name='uq_telegram_vacancy_channel_message'),
    sa.UniqueConstraint('hash'),
    schema='vacancy_parser'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_vacancy', schema='vacancy_parser')
    # ### end Alembic commands ###
