"""added fingerprint and trgm extension

Revision ID: e14658717c09
Revises: 3e4cb987a691
Create Date: 2025-06-25 20:56:17.121130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14658717c09'
down_revision: Union[str, Sequence[str], None] = '3e4cb987a691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_vacancy', sa.Column('fingerprint', sa.Text(), nullable=False), schema='vacancy_parser')
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_vacancy', 'fingerprint', schema='vacancy_parser')
    # ### end Alembic commands ###
