"""changed indexes

Revision ID: e9ce949727cc
Revises: e2891e724dc8
Create Date: 2025-08-20 08:16:48.965314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e9ce949727cc'
down_revision: Union[str, Sequence[str], None] = 'e2891e724dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True), schema='vacancy_parser')
    op.drop_index(op.f('ix_vacancy_parser_vacancies_deleted_at'), table_name='vacancies', schema='vacancy_parser')
    op.create_index('idx_vacancies_not_processed', 'vacancies', ['processed_at'], unique=False, schema='vacancy_parser', postgresql_where='processed_at IS NULL')
    op.create_index(op.f('ix_vacancy_parser_vacancies_processed_at'), 'vacancies', ['processed_at'], unique=False, schema='vacancy_parser')
    op.create_index(op.f('ix_vacancy_parser_vacancies_published_at'), 'vacancies', ['published_at'], unique=False, schema='vacancy_parser')
    op.drop_column('vacancies', 'deleted_at', schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='vacancy_parser')
    op.drop_index(op.f('ix_vacancy_parser_vacancies_published_at'), table_name='vacancies', schema='vacancy_parser')
    op.drop_index(op.f('ix_vacancy_parser_vacancies_processed_at'), table_name='vacancies', schema='vacancy_parser')
    op.drop_index('idx_vacancies_not_processed', table_name='vacancies', schema='vacancy_parser', postgresql_where='processed_at IS NULL')
    op.create_index(op.f('ix_vacancy_parser_vacancies_deleted_at'), 'vacancies', ['deleted_at'], unique=False, schema='vacancy_parser')
    op.drop_column('vacancies', 'processed_at', schema='vacancy_parser')
    # ### end Alembic commands ###
