"""added id field for vacancy

Revision ID: 24eb94a9b6db
Revises: 0dda3e0ff261
Create Date: 2025-06-30 16:14:20.526863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24eb94a9b6db'
down_revision: Union[str, Sequence[str], None] = '0dda3e0ff261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_vacancy', sa.Column('id', sa.Integer(), nullable=False), schema='vacancy_parser')
    op.create_unique_constraint("uq_telegram_vacancy_hash", 'telegram_vacancy', ['hash'], schema='vacancy_parser')
    op.create_unique_constraint("uq_telegram_vacancy_fingerprint", 'telegram_vacancy', ['fingerprint'], schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_telegram_vacancy_hash", 'telegram_vacancy', schema='vacancy_parser', type_='unique')
    op.drop_constraint("uq_telegram_vacancy_fingerprint", 'telegram_vacancy', schema='vacancy_parser', type_='unique')
    op.drop_column('telegram_vacancy', 'id', schema='vacancy_parser')
    # ### end Alembic commands ###
