"""added head hunter vacancy

Revision ID: deed44d1cc69
Revises: 22bb94e53640
Create Date: 2025-08-06 12:54:08.432135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deed44d1cc69'
down_revision: Union[str, Sequence[str], None] = '22bb94e53640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('head_hunter_vacancy',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['vacancy_parser.source.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('link'),
    schema='vacancy_parser'
    )
    op.create_index(op.f('ix_vacancy_parser_head_hunter_vacancy_deleted_at'), 'head_hunter_vacancy', ['deleted_at'], unique=False, schema='vacancy_parser')
    op.create_index(op.f('ix_vacancy_parser_head_hunter_vacancy_source_id'), 'head_hunter_vacancy', ['source_id'], unique=False, schema='vacancy_parser')
    op.alter_column('telegram_vacancy', 'data',
               existing_type=sa.VARCHAR(length=8192),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_vacancy', 'data',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=8192),
               existing_nullable=False,
               schema='vacancy_parser')
    op.drop_index(op.f('ix_vacancy_parser_head_hunter_vacancy_source_id'), table_name='head_hunter_vacancy', schema='vacancy_parser')
    op.drop_index(op.f('ix_vacancy_parser_head_hunter_vacancy_deleted_at'), table_name='head_hunter_vacancy', schema='vacancy_parser')
    op.drop_table('head_hunter_vacancy', schema='vacancy_parser')
    # ### end Alembic commands ###
