"""added telegram vacancy

Revision ID: 8e716b7b2801
Revises: 0d01a329e26b
Create Date: 2025-06-23 09:22:38.091246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e716b7b2801'
down_revision: Union[str, Sequence[str], None] = '0d01a329e26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_vacancy',
    sa.Column('channel_username', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Enum('TELEGRAM', 'HH', name='vacancysource'), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.Column('data', sa.String(length=8192), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hash'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('link'),
    schema='vacancy_parser'
    )
    op.create_index(op.f('ix_vacancy_parser_telegram_vacancy_source'), 'telegram_vacancy', ['source'], unique=False, schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_parser_telegram_vacancy_source'), table_name='telegram_vacancy', schema='vacancy_parser')
    op.drop_table('telegram_vacancy', schema='vacancy_parser')
    # ### end Alembic commands ###
