"""removed fingerprint index

Revision ID: e2891e724dc8
Revises: cd882321b33c
Create Date: 2025-08-20 08:02:56.646041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2891e724dc8'
down_revision: Union[str, Sequence[str], None] = 'cd882321b33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vacancies_fingerprint_key'), 'vacancies', schema='vacancy_parser', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('vacancies_fingerprint_key'), 'vacancies', ['fingerprint'], schema='vacancy_parser', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
