"""changed created at to published at to vacancy

Revision ID: 22bb94e53640
Revises: 3ca3861dda92
Create Date: 2025-07-26 17:18:09.069076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '22bb94e53640'
down_revision: Union[str, Sequence[str], None] = '3ca3861dda92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_vacancy', sa.Column('published_at', sa.DateTime(timezone=True), nullable=False), schema='vacancy_parser')
    op.drop_column('telegram_vacancy', 'created_at', schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_vacancy', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False), schema='vacancy_parser')
    op.drop_column('telegram_vacancy', 'published_at', schema='vacancy_parser')
    # ### end Alembic commands ###
