"""added deleted_at to vacancy

Revision ID: 0dda3e0ff261
Revises: e14658717c09
Create Date: 2025-06-26 14:18:29.861862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dda3e0ff261'
down_revision: Union[str, Sequence[str], None] = 'e14658717c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_vacancy', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True), schema='vacancy_parser')
    op.create_index(op.f('ix_vacancy_parser_telegram_vacancy_deleted_at'), 'telegram_vacancy', ['deleted_at'], unique=False, schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_parser_telegram_vacancy_deleted_at'), table_name='telegram_vacancy', schema='vacancy_parser')
    op.drop_column('telegram_vacancy', 'deleted_at', schema='vacancy_parser')
    # ### end Alembic commands ###
