"""added models

Revision ID: 3ca3861dda92
Revises: b040edb2dcb1
Create Date: 2025-06-30 17:03:01.604131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca3861dda92'
down_revision: Union[str, Sequence[str], None] = 'b040edb2dcb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='vacancy_parser'
    )
    op.create_table('telegram_vacancy',
    sa.Column('channel_username', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.Column('data', sa.String(length=8192), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['vacancy_parser.source.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('link'),
    schema='vacancy_parser'
    )
    op.create_index(op.f('ix_vacancy_parser_telegram_vacancy_deleted_at'), 'telegram_vacancy', ['deleted_at'], unique=False, schema='vacancy_parser')
    op.create_index(op.f('ix_vacancy_parser_telegram_vacancy_source_id'), 'telegram_vacancy', ['source_id'], unique=False, schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_parser_telegram_vacancy_source_id'), table_name='telegram_vacancy', schema='vacancy_parser')
    op.drop_index(op.f('ix_vacancy_parser_telegram_vacancy_deleted_at'), table_name='telegram_vacancy', schema='vacancy_parser')
    op.drop_table('telegram_vacancy', schema='vacancy_parser')
    op.drop_table('source', schema='vacancy_parser')
    # ### end Alembic commands ###
