"""added telegram vacancy

Revision ID: a197384e0d5c
Revises: b040edb2dcb1
Create Date: 2025-06-24 11:51:15.996424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a197384e0d5c'
down_revision: Union[str, Sequence[str], None] = 'b040edb2dcb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_vacancy',
    sa.Column('channel_username', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Enum('TELEGRAM', 'HH', name='vacancysource', schema='vacancy_parser'), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.Column('data', sa.String(length=8192), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hash'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('link'),
    schema='vacancy_parser'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_vacancy', schema='vacancy_parser')
    # ### end Alembic commands ###
