from database.models.enums import BaseAliasEnum


__all__ = ["SkillEnum"]


class SkillEnum(BaseAliasEnum):
    __validate_ordering__ = True

    UNKNOWN = "Неизвестно"

    AGILE = "Agile"
    AIRFLOW = "Airflow"
    ANGULAR = "Angular"
    ANSIBLE = "Ansible"
    AWS = "AWS"
    AZURE = "Azure"
    BASH = "Bash"
    BIG_DATA = "Big Data"
    BPMN = "BPMN"
    CPP = "C++"
    CELERY = "Celery"
    CI_CD = "CI/CD", ("gitlab ci",)
    CLICKHOUSE = "ClickHouse"
    CONFLUENCE = "Confluence"
    CSS = "CSS", ("css3",)
    CYPRESS = "Cypress"
    C_SHARP = "C#"
    DEVOPS = "DevOps"
    DJANGO = "Django", ("drf",)
    DOCKER = "Docker"
    DOCKER_COMPOSE = "Docker Compose"
    ELASTICSEARCH = "Elasticsearch", ("elk",)
    ETL = "ETL"
    ENGLISH = "Английский язык"
    FAST_API = "FastAPI"
    FIGMA = "Figma"
    FLASK = "Flask"
    GIT = "Git"
    GITLAB = "GitLab"
    GO = "Go", ("golang",)
    GRPC = "gRPC"
    GRAFANA = "Grafana"
    GRAPHQL = "GraphQL"
    HELM = "Helm"
    HTML = "HTML", ("html5",)
    HTTP = "HTTP"
    HADOOP = "Hadoop"
    JAVA = "Java"
    JAVASCRIPT = "JavaScript"
    JENKINS = "Jenkins"
    JEST = "Jest"
    JIRA = "Jira", ("atlassian jira",)
    JSON = "JSON"
    JUNIT = "JUnit"
    JQUERY = "jQuery"
    KANBAN = "Kanban"
    KAFKA = "Kafka", ("apache kafka",)
    KOTLIN = "Kotlin"
    KUBERNETES = "Kubernetes"
    LARAVEL = "Laravel"
    LINUX = "Linux"
    LLM = "LLM"
    MLFLOW = "MLflow"
    MONGODB = "MongoDB"
    MS_SQL = "MS SQL"
    MYSQL = "MySQL"
    MICROSERVICES = "Микросервисы"
    MAVEN = "Maven"
    NEXT_JS = "Next.js"
    NGINX = "Nginx"
    NODE_JS = "Node.js"
    NOSQL = "NoSQL"
    OOP = "ООП", ("oop",)
    PANDAS = "pandas"
    PHP = "PHP"
    POSTGIS = "PostGIS"
    POSTGRESQL = "PostgreSQL"
    POSTMAN = "Postman"
    POWER_BI = "Power BI"
    PROMETHEUS = "Prometheus"
    PYTHON = "Python"
    PYTORCH = "PyTorch"
    QA = "QA"
    RABBITMQ = "RabbitMQ"
    REACT = "React"
    REDIS = "Redis"
    REDUX = "Redux"
    REQUESTS = "requests"
    REST_API = "REST API", ("rest", "api", "restful api", "restful")
    SCRUM = "SCRUM"
    SCALA = "Scala"
    SCSS = "SCSS"
    SELENIUM = "Selenium"
    SQL = "SQL"
    SQLALCHEMY = "SQLAlchemy"
    SWAGGER = "Swagger"
    SWIFT = "Swift"
    SYMFONY = "Symfony"
    SOAP = "SOAP"
    SOLID = "SOLID"
    SPRING = "Spring", ("spring framework",)
    SPARK = "Spark", ("apache spark", "pyspark")
    SPA = "SPA"
    TAILWIND = "Tailwind"
    TCP_IP = "TCP/IP"
    TERRAFORM = "Terraform"
    TYPESCRIPT = "TypeScript"
    UML = "UML"
    VUE_JS = "Vue.js", ("vue", "vuejs")
    WEBSOCKET = "WebSocket"
    WEBPACK = "Webpack"
    WINDOWS = "Windows"
    XML = "XML"
    YANDEX_CLOUD = "Yandex Cloud"
    ZABBIX = "Zabbix"
