services:
  gpt-api:
    container_name: gpt-api
    build:
      context: ${PROJECT_ROOT}
      dockerfile: infra/docker/gpt-api/Dockerfile
      target: ${ENV_MODE}
    env_file: ${PROJECT_ROOT}/infra/.env
    ports:
      - "${GPT_API_PORT}:${GPT_API_PORT}"
    volumes:
      - ${PROJECT_ROOT}/services/gpt-api/src:/app/services/gpt-api/src
      - ${PROJECT_ROOT}/libs:/app/libs
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://gpt-api:${GPT_API_PORT}/health" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
