[project]
name = "telegram-api"
dynamic = ["version"]
dependencies = [
    "beautifulsoup4>=4.13.4",
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "pydantic-settings>=2.10.0",
    "uvicorn[standard]>=0.34.3",
]
