"""added published_at field

Revision ID: 6bc849bed60f
Revises: 27443a5c29d6
Create Date: 2025-07-26 17:41:49.208292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc849bed60f'
down_revision: Union[str, Sequence[str], None] = '27443a5c29d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='vacancy_processor')
    op.add_column('vacancy', sa.Column('published_at', sa.DateTime(timezone=True), nullable=False), schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'published_at', schema='vacancy_processor')
    op.alter_column('skill', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='vacancy_processor')
    # ### end Alembic commands ###
