"""added vacancy company name

Revision ID: 82e1a78ab67d
Revises: 58fcea6d1d6b
Create Date: 2025-08-06 16:28:40.003417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e1a78ab67d'
down_revision: Union[str, Sequence[str], None] = '58fcea6d1d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('company_name', sa.String(length=64), nullable=True), schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'company_name', schema='vacancy_processor')
    # ### end Alembic commands ###
