"""added vacancy salary

Revision ID: 58fcea6d1d6b
Revises: 6bc849bed60f
Create Date: 2025-08-06 16:08:17.741212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58fcea6d1d6b'
down_revision: Union[str, Sequence[str], None] = '6bc849bed60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('salary', sa.String(length=32), nullable=True), schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'salary', schema='vacancy_processor')
    # ### end Alembic commands ###
