"""nullable vacancy fields

Revision ID: 27443a5c29d6
Revises: 0a49a36dd5a3
Create Date: 2025-07-11 07:27:54.553598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27443a5c29d6'
down_revision: Union[str, Sequence[str], None] = '0a49a36dd5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'workplace_description',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'workplace_description',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='vacancy_processor')
    # ### end Alembic commands ###
