"""added vacancy fields

Revision ID: 0a49a36dd5a3
Revises: 5e788f22fc16
Create Date: 2025-07-03 06:16:16.205603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a49a36dd5a3'
down_revision: Union[str, Sequence[str], None] = '5e788f22fc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('workplace_description', sa.Text(), nullable=False), schema='vacancy_processor')
    op.add_column('vacancy', sa.Column('responsibilities', sa.Text(), nullable=False), schema='vacancy_processor')
    op.add_column('vacancy', sa.Column('requirements', sa.Text(), nullable=False), schema='vacancy_processor')
    op.add_column('vacancy', sa.Column('conditions', sa.Text(), nullable=False), schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'conditions', schema='vacancy_processor')
    op.drop_column('vacancy', 'requirements', schema='vacancy_processor')
    op.drop_column('vacancy', 'responsibilities', schema='vacancy_processor')
    op.drop_column('vacancy', 'workplace_description', schema='vacancy_processor')
    # ### end Alembic commands ###
