"""increased comany name

Revision ID: cd68dcb3d5d0
Revises: c2f4cc1a2bba
Create Date: 2025-08-15 20:34:44.263614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd68dcb3d5d0'
down_revision: Union[str, Sequence[str], None] = 'c2f4cc1a2bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'company_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True,
               schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'company_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True,
               schema='vacancy_processor')
    # ### end Alembic commands ###
