"""increased salary charfield

Revision ID: 591bd2830ec5
Revises: 9aa2397e6d0b
Create Date: 2025-08-17 09:13:22.473625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591bd2830ec5'
down_revision: Union[str, Sequence[str], None] = '9aa2397e6d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'salary',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=96),
               existing_nullable=True,
               schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'salary',
               existing_type=sa.String(length=96),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True,
               schema='vacancy_processor')
    # ### end Alembic commands ###
