"""added source and link index

Revision ID: 04aba408cd35
Revises: 599a7f46753f
Create Date: 2025-08-20 08:53:17.803409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04aba408cd35'
down_revision: Union[str, Sequence[str], None] = '599a7f46753f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vacancy_link_key'), 'vacancy', schema='vacancy_processor', type_='unique')
    op.create_index('idx_vacancy_published_at_id', 'vacancy', ['published_at', 'id'], unique=False, schema='vacancy_processor')
    op.create_index('idx_vacancy_source_link', 'vacancy', ['source', 'link'], unique=True, schema='vacancy_processor')
    op.create_index(op.f('ix_vacancy_processor_vacancy_published_at'), 'vacancy', ['published_at'], unique=False, schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_processor_vacancy_published_at'), table_name='vacancy', schema='vacancy_processor')
    op.drop_index('idx_vacancy_source_link', table_name='vacancy', schema='vacancy_processor')
    op.drop_index('idx_vacancy_published_at_id', table_name='vacancy', schema='vacancy_processor')
    op.create_unique_constraint(op.f('vacancy_link_key'), 'vacancy', ['link'], schema='vacancy_processor', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
