"""added source

Revision ID: 599a7f46753f
Revises: 591bd2830ec5
Create Date: 2025-08-20 08:10:03.270849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599a7f46753f'
down_revision: Union[str, Sequence[str], None] = '591bd2830ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('source', sa.String(length=16), nullable=False), schema='vacancy_processor')
    op.create_index(op.f('ix_vacancy_processor_vacancy_source'), 'vacancy', ['source'], unique=False, schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_processor_vacancy_source'), table_name='vacancy', schema='vacancy_processor')
    op.drop_column('vacancy', 'source', schema='vacancy_processor')
    # ### end Alembic commands ###
