"""removed skill category

Revision ID: 07e18d0f7ca7
Revises: 04aba408cd35
Create Date: 2025-08-21 09:19:33.951801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e18d0f7ca7'
down_revision: Union[str, Sequence[str], None] = '04aba408cd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_category', schema='vacancy_processor')
    op.drop_constraint(op.f('skill_category_id_fkey'), 'skill', schema='vacancy_processor', type_='foreignkey')
    op.drop_column('skill', 'category_id', schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='vacancy_processor')
    op.create_foreign_key(op.f('skill_category_id_fkey'), 'skill', 'skill_category', ['category_id'], ['id'], source_schema='vacancy_processor', referent_schema='vacancy_processor', ondelete='CASCADE')
    op.create_table('skill_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_category_pkey')),
    sa.UniqueConstraint('name', name=op.f('skill_category_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='vacancy_processor'
    )
    # ### end Alembic commands ###
