[project]
name = "vacancy-processor"
dynamic = ["version"]
dependencies = [
    "alembic>=1.16.2",
    "asyncpg>=0.30.0",
    "httpx>=0.28.1",
    "sqlalchemy>=2.0.41",
    "uvloop>=0.21.0", # remove after adding fastapi?
]

[dependency-groups]
dev = [
    "hupper>=1.12.1",
]
