services:
  vacancy-processor:
    container_name: vacancy-processor
    build:
      context: ${PROJECT_ROOT}
      dockerfile: infra/docker/vacancy-processor/Dockerfile
      target: ${ENV_MODE}
    env_file: ${PROJECT_ROOT}/infra/.env
    volumes:
      - ${PROJECT_ROOT}/services/vacancy-processor/src:/app/services/vacancy-processor/src
      - ${PROJECT_ROOT}/libs:/app/libs
    networks:
      - app-network
