x-service-common: &service-common
  build:
    context: ${PROJECT_ROOT}
    dockerfile: infra/docker/vacancy-processor/Dockerfile
    target: ${ENV_MODE}
  env_file: ${PROJECT_ROOT}/infra/.env
  volumes:
    - ${PROJECT_ROOT}/services/vacancy-processor:/app/services/vacancy-processor
    - ${PROJECT_ROOT}/libs:/app/libs
  networks:
    - app-network

x-healthcheck-common: &healthcheck-common
  interval: 30s
  timeout: 3s
  retries: 3
  start_period: 3s
  start_interval: 1s

services:
  vacancy-processor:
    <<: *service-common
    container_name: vacancy-processor
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://vacancy-processor:${ENV_SERVICE_INTERNAL_PORT}/health" ]
      <<: *healthcheck-common

  vacancy-processor-worker:
    <<: *service-common
    container_name: vacancy-processor-worker
    command: [ "celery", "-A", "celery_app.app", "worker", "-n", "vacancy_processor", "-l", "${LOG_LEVEL}" ]
    healthcheck:
      test: [ "CMD-SHELL", "celery -A celery_app.app inspect ping -d celery@vacancy_processor" ]
      <<: *healthcheck-common

  vacancy-processor-beat:
    <<: *service-common
    container_name: vacancy-processor-beat
    command: [ "celery", "-A", "celery_app.app", "beat", "-l", "${LOG_LEVEL}" ]
