"""

Commit message: added telegram vacancy
Revision ID: 3a9e55c63e04
Revises: ee7ce470e504
Create Date: 2025-06-19 23:00:28.697636

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "3a9e55c63e04"
down_revision: str | None = "ee7ce470e504"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("telegram_vacancy",
    sa.Column("channel_link", sa.String(length=143), nullable=False),
    sa.Column("message_id", sa.Integer(), nullable=False),
    sa.Column("message", sa.String(length=4096), nullable=False),
    sa.Column("hash", sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint("hash"),
    sa.UniqueConstraint("channel_link", "message_id", name="uq_telegram_vacancy_channel_message"),
    sa.UniqueConstraint("hash"),
    schema="vacancy_parser"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_vacancy", schema="vacancy_parser")
    # ### end Alembic commands ###
