"""

Commit message: added vacancy
Revision ID: d0b2c5c8b75e
Revises: 3a9e55c63e04
Create Date: 2025-06-19 23:09:36.428224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0b2c5c8b75e'
down_revision: Union[str, None] = '3a9e55c63e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('hash'),
    sa.UniqueConstraint('hash'),
    schema='vacancy_parser'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_vacancy', schema='vacancy_parser')
    # ### end Alembic commands ###
